import Foundation
import Honeybadger

enum Mode: String {
    case notice
    case crash
    case replay
}

struct Options {
    var mode: Mode = .notice
    var apiKey: String?
    var environment = "production-smoke"
    var marker: String?
    var revision: String?
    var waitSeconds: TimeInterval = 15
}

func usage() {
    print("""
    Usage:
      HONEYBADGER_API_KEY=<project-api-key> swift run HoneybadgerProductionSmoke [mode] [options]

    Modes:
      notice                Send one handled notice. This is the default.
      crash                 Configure Honeybadger, set context, then intentionally SIGSEGV.
      replay                Relaunch after crash mode and wait for the pending signal report send.

    Options:
      --api-key <key>        Honeybadger project API key. Prefer HONEYBADGER_API_KEY.
      --environment <name>   Environment sent with the notice. Default: production-smoke
      --marker <value>       Unique marker/fingerprint. Generated by default.
      --revision <value>     Optional revision sent as server.revision. Defaults to marker.
      --wait-seconds <n>     Seconds to wait for the async API response. Default: 15
      --help                 Show this help.
    """)
}

func parseOptions(_ rawArgs: [String]) -> Options? {
    var args = rawArgs
    var options = Options(apiKey: ProcessInfo.processInfo.environment["HONEYBADGER_API_KEY"])

    if let first = args.first, !first.hasPrefix("--") {
        guard let mode = Mode(rawValue: first) else {
            print("Unknown mode: \(first)")
            return nil
        }
        options.mode = mode
        args.removeFirst()
    }

    var index = 0
    while index < args.count {
        let arg = args[index]
        switch arg {
        case "--help", "-h":
            usage()
            exit(0)
        case "--api-key":
            guard index + 1 < args.count else { return nil }
            options.apiKey = args[index + 1]
            index += 2
        case "--environment":
            guard index + 1 < args.count else { return nil }
            options.environment = args[index + 1]
            index += 2
        case "--marker":
            guard index + 1 < args.count else { return nil }
            options.marker = args[index + 1]
            index += 2
        case "--revision":
            guard index + 1 < args.count else { return nil }
            options.revision = args[index + 1]
            index += 2
        case "--wait-seconds":
            guard index + 1 < args.count, let value = Double(args[index + 1]), value > 0 else { return nil }
            options.waitSeconds = value
            index += 2
        default:
            print("Unknown option: \(arg)")
            return nil
        }
    }

    return options
}

func crashReportDirectory() -> URL? {
    guard let caches = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first else {
        return nil
    }
    return caches.appendingPathComponent("HoneybadgerCrashReports", isDirectory: true)
}

func files(in directory: URL?) -> Set<URL> {
    guard let directory else { return [] }
    let urls = (try? FileManager.default.contentsOfDirectory(
        at: directory,
        includingPropertiesForKeys: nil
    )) ?? []
    return Set(urls)
}

func jsonReports(in directory: URL?) -> Set<URL> {
    files(in: directory).filter { $0.lastPathComponent.hasSuffix(".json") }
}

func signalCrashFile(in directory: URL?) -> URL? {
    directory?.appendingPathComponent("signal_crash.bin")
}

func waitForSendCompletion(report: URL, timeout: TimeInterval) -> Bool {
    let deadline = Date().addingTimeInterval(timeout)
    while Date() < deadline {
        if !FileManager.default.fileExists(atPath: report.path) {
            return true
        }
        Thread.sleep(forTimeInterval: 0.25)
    }
    return !FileManager.default.fileExists(atPath: report.path)
}

func waitForSignalReplayCompletion(directory: URL?, initialReports: Set<URL>, timeout: TimeInterval) -> Bool {
    let deadline = Date().addingTimeInterval(timeout)
    var seenConvertedReport = false

    while Date() < deadline {
        let currentReports = jsonReports(in: directory)
        let convertedReports = currentReports
            .subtracting(initialReports)
            .filter { $0.lastPathComponent.hasPrefix("crash_signal_") }

        if !convertedReports.isEmpty {
            seenConvertedReport = true
        }

        let signalBinExists = signalCrashFile(in: directory).map {
            FileManager.default.fileExists(atPath: $0.path)
        } ?? false

        if !signalBinExists && convertedReports.isEmpty && seenConvertedReport {
            return true
        }

        // The send can complete between polling intervals: the .bin is gone, the
        // transient converted .json is already deleted, and no pending signal
        // report remains.
        if !signalBinExists && convertedReports.isEmpty {
            Thread.sleep(forTimeInterval: 0.5)
            let settledReports = jsonReports(in: directory)
                .subtracting(initialReports)
                .filter { $0.lastPathComponent.hasPrefix("crash_signal_") }
            if settledReports.isEmpty {
                return true
            }
        }

        Thread.sleep(forTimeInterval: 0.25)
    }

    return false
}

func configureHoneybadger(apiKey: String, environment: String, revision: String) {
    Honeybadger.configure(apiKey: apiKey, environment: environment, revision: revision)
}

func setSmokeContext(marker: String, mode: Mode, waitSeconds: TimeInterval) {
    Honeybadger.setContext(context: [
        "sample_app": "HoneybadgerProductionSmoke",
        "sample_mode": mode.rawValue,
        "marker": marker,
        "os_version": ProcessInfo.processInfo.operatingSystemVersionString,
        "wait_seconds": String(Int(waitSeconds))
    ])
}

@inline(never)
func triggerHoneybadgerProductionSmokeSignalCrash() -> Never {
    let pointer = UnsafeMutablePointer<UInt8>(bitPattern: 0x1)!
    pointer.pointee = 0x42
    fatalError("unreachable after intentional SIGSEGV")
}

@inline(never)
func enterHoneybadgerProductionSmokeSignalCrash() -> Never {
    triggerHoneybadgerProductionSmokeSignalCrash()
}

let args = Array(CommandLine.arguments.dropFirst())
guard let options = parseOptions(args) else {
    usage()
    exit(2)
}

guard let apiKey = options.apiKey?.trimmingCharacters(in: .whitespacesAndNewlines), !apiKey.isEmpty else {
    print("Missing API key. Set HONEYBADGER_API_KEY or pass --api-key.")
    exit(2)
}

let marker = options.marker ?? "production-smoke-\(UUID().uuidString)"
let revision = options.revision ?? marker
let directory = crashReportDirectory()

print("Honeybadger production smoke sample")
print("Mode: \(options.mode.rawValue)")
print("Environment: \(options.environment)")
print("Revision: \(revision)")
print("Marker: \(marker)")
if let directory {
    print("Pending report directory: \(directory.path)")
}

switch options.mode {
case .notice:
    configureHoneybadger(apiKey: apiKey, environment: options.environment, revision: revision)
    setSmokeContext(marker: marker, mode: .notice, waitSeconds: options.waitSeconds)

    let before = jsonReports(in: directory)
    Honeybadger.notify(
        errorString: "Honeybadger production smoke test notice \(marker)",
        errorClass: "HoneybadgerProductionSmoke",
        context: [
            "marker": marker,
            "sample_mode": "notice",
            "wait_seconds": String(Int(options.waitSeconds))
        ],
        fingerprint: marker
    )

    let newReports = jsonReports(in: directory)
        .subtracting(before)
        .filter { $0.lastPathComponent.hasSuffix(".json") }

    guard let report = newReports.sorted(by: { $0.lastPathComponent < $1.lastPathComponent }).first else {
        print("No new pending report file was observed after notify().")
        print("Check the Honeybadger project for marker: \(marker)")
        exit(3)
    }

    print("Created pending report: \(report.lastPathComponent)")
    print("Waiting up to \(Int(options.waitSeconds))s for production API acceptance...")

    if waitForSendCompletion(report: report, timeout: options.waitSeconds) {
        print("Production API accepted the notice; pending report was removed.")
        print("Search Honeybadger for marker/fingerprint: \(marker)")
        exit(0)
    }

    print("The pending report still exists after \(Int(options.waitSeconds))s.")
    print("That usually means the API request failed, timed out, or has not completed yet.")
    print("Report file: \(report.path)")
    print("Search Honeybadger for marker/fingerprint in case the response arrived late: \(marker)")
    exit(1)

case .crash:
    configureHoneybadger(apiKey: apiKey, environment: options.environment, revision: revision)
    setSmokeContext(marker: marker, mode: .crash, waitSeconds: options.waitSeconds)
    print("About to intentionally crash with SIGSEGV.")
    fflush(stdout)
    enterHoneybadgerProductionSmokeSignalCrash()

case .replay:
    let before = jsonReports(in: directory)
    configureHoneybadger(apiKey: apiKey, environment: options.environment, revision: revision)
    print("Waiting up to \(Int(options.waitSeconds))s for pending signal report acceptance...")

    if waitForSignalReplayCompletion(directory: directory, initialReports: before, timeout: options.waitSeconds) {
        print("Production API accepted the signal crash report; pending signal report was removed.")
        print("Search Honeybadger for marker/fingerprint: \(marker)")
        print("Expected symbolicated frame includes: triggerHoneybadgerProductionSmokeSignalCrash")
        exit(0)
    }

    print("A pending signal report still exists after \(Int(options.waitSeconds))s.")
    if let directory {
        print("Pending report directory: \(directory.path)")
    }
    print("Search Honeybadger for marker/fingerprint in case the response arrived late: \(marker)")
    exit(1)
}
