#!/bin/bash
#
# Builds the production smoke executable, creates/uploads its dSYM, runs a real
# SIGSEGV crash, relaunches to send the pending signal report, and prints the
# marker to find in Honeybadger.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

API_KEY="${HONEYBADGER_API_KEY:-}"
ENVIRONMENT="production-smoke"
MARKER=""
REVISION=""
WAIT_SECONDS="30"
CONFIGURATION="debug"
SKIP_DSYM_UPLOAD=0
CONTINUE_WITHOUT_DSYM=0

usage() {
    cat <<'USAGE'
Usage:
  HONEYBADGER_API_KEY=<project-api-key> Examples/ProductionSmokeTest/run_signal_smoke.sh [options]

Options:
  --api-key <key>          Honeybadger project API key. Prefer HONEYBADGER_API_KEY.
  --environment <name>     Environment sent with the crash report. Default: production-smoke
  --marker <value>         Unique marker/fingerprint. Generated by default.
  --revision <value>       Revision used for SDK payload and dSYM upload. Defaults to marker.
  --wait-seconds <n>       Seconds to wait for report acceptance. Default: 30
  --configuration <name>   SwiftPM configuration: debug or release. Default: debug
  --skip-dsym-upload       Build and run the crash/replay flow without uploading dSYMs.
  --continue-without-dsym  Run crash/replay even if dSYM upload fails.
  --help                   Show this help.
USAGE
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --api-key)
            API_KEY="$2"
            shift 2
            ;;
        --environment)
            ENVIRONMENT="$2"
            shift 2
            ;;
        --marker)
            MARKER="$2"
            shift 2
            ;;
        --revision)
            REVISION="$2"
            shift 2
            ;;
        --wait-seconds)
            WAIT_SECONDS="$2"
            shift 2
            ;;
        --configuration)
            CONFIGURATION="$2"
            shift 2
            ;;
        --skip-dsym-upload)
            SKIP_DSYM_UPLOAD=1
            shift 1
            ;;
        --continue-without-dsym)
            CONTINUE_WITHOUT_DSYM=1
            shift 1
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            usage
            exit 2
            ;;
    esac
done

if [[ -z "$API_KEY" ]]; then
    echo "Missing API key. Set HONEYBADGER_API_KEY or pass --api-key."
    exit 2
fi

if [[ "$CONFIGURATION" != "debug" && "$CONFIGURATION" != "release" ]]; then
    echo "Unsupported --configuration: $CONFIGURATION"
    exit 2
fi

for dep in swift dsymutil dwarfdump; do
    if ! command -v "$dep" >/dev/null 2>&1; then
        echo "Required tool not found in PATH: $dep"
        exit 2
    fi
done

if [[ -z "$MARKER" ]]; then
    if command -v uuidgen >/dev/null 2>&1; then
        MARKER="production-signal-smoke-$(uuidgen)"
    else
        MARKER="production-signal-smoke-$(date +%s)"
    fi
fi

if [[ -z "$REVISION" ]]; then
    REVISION="$MARKER"
fi

WORK="$(mktemp -d)"
cleanup() {
    rm -rf "$WORK"
}
trap cleanup EXIT

echo "Honeybadger production signal smoke"
echo "Environment: $ENVIRONMENT"
echo "Revision: $REVISION"
echo "Marker: $MARKER"
echo "Configuration: $CONFIGURATION"

cd "$REPO_ROOT"

echo ""
echo "Building sample executable..."
swift build -c "$CONFIGURATION" --product HoneybadgerProductionSmoke
BIN_DIR="$(swift build -c "$CONFIGURATION" --show-bin-path)"
BIN="$BIN_DIR/HoneybadgerProductionSmoke"

if [[ ! -x "$BIN" ]]; then
    echo "Built executable not found: $BIN"
    exit 1
fi

DSYM_DIR="$WORK/dsyms"
mkdir -p "$DSYM_DIR"
DSYM="$DSYM_DIR/HoneybadgerProductionSmoke.dSYM"

echo ""
echo "Creating dSYM..."
dsymutil "$BIN" -o "$DSYM"
dwarfdump --uuid "$DSYM"

if [[ $SKIP_DSYM_UPLOAD -eq 0 ]]; then
    echo ""
    echo "Uploading dSYM to Honeybadger..."
    set +e
    bash "$REPO_ROOT/bin/upload-dsyms.sh" \
        --api-key "$API_KEY" \
        --dsym-path "$DSYM_DIR" \
        --revision "$REVISION"
    UPLOAD_STATUS=$?
    set -e
    if [[ $UPLOAD_STATUS -ne 0 ]]; then
        if [[ $CONTINUE_WITHOUT_DSYM -eq 1 ]]; then
            echo "dSYM upload failed, continuing to crash/replay because --continue-without-dsym was set."
            echo "The crash report may be accepted but will probably not symbolicate."
        else
            echo "dSYM upload failed, so the crash phase was not run."
            echo "Fix dSYM upload first, or pass --continue-without-dsym to test crash reporting without symbolication."
            exit "$UPLOAD_STATUS"
        fi
    fi
else
    echo ""
    echo "Skipping dSYM upload by request."
fi

export HOME="$WORK/home"
export CFFIXED_USER_HOME="$HOME"
mkdir -p "$HOME"
REPORT_DIR="$HOME/Library/Caches/HoneybadgerCrashReports"

echo ""
echo "Running crash phase. A segmentation fault message is expected..."
set +e
"$BIN" crash \
    --api-key "$API_KEY" \
    --environment "$ENVIRONMENT" \
    --marker "$MARKER" \
    --revision "$REVISION" \
    --wait-seconds "$WAIT_SECONDS"
CRASH_STATUS=$?
set -e

if [[ $CRASH_STATUS -eq 0 ]]; then
    echo "Crash phase unexpectedly exited 0."
    exit 1
fi

if [[ ! -f "$REPORT_DIR/signal_crash.bin" ]]; then
    echo "signal_crash.bin was not written at: $REPORT_DIR"
    exit 1
fi

echo ""
echo "Running replay phase..."
"$BIN" replay \
    --api-key "$API_KEY" \
    --environment "$ENVIRONMENT" \
    --marker "$MARKER" \
    --revision "$REVISION" \
    --wait-seconds "$WAIT_SECONDS"

echo ""
echo "Done. Search Honeybadger for marker/fingerprint:"
echo "$MARKER"
if [[ $SKIP_DSYM_UPLOAD -eq 0 ]]; then
    echo "Expected symbolicated frame includes: triggerHoneybadgerProductionSmokeSignalCrash"
else
    echo "dSYM upload was skipped, so the report may show raw addresses."
fi
